format:
    rg --files -g '*.{hh,cc}' -0 | xargs -0 clang-format -i

bootstrap:
    cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    ln -sfn build/compile_commands.json compile_commands.json

build: bootstrap
    cmake --build build

tun: bootstrap
    cmake -B build -DNETSTACK_ENABLE_TUN=ON
    cmake --build build

test: build
    ctest --test-dir build

clean:
    rm -rf build build*
    rm -rf compile_commands.json