function(lanp2p_apply_defaults target)
  target_compile_features(${target} PUBLIC cxx_std_17)
  set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF)
  if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
  endif()
endfunction()

function(lanp2p_link_boost target)
  if(TARGET Boost::headers)
    target_link_libraries(${target} PUBLIC Boost::headers)
  else()
    target_include_directories(${target} PUBLIC ${Boost_INCLUDE_DIRS})
  endif()
endfunction()
